-- MySQL Script generated by MySQL Workbench
-- 10/20/14 12:59:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myMailItemEventManagement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myMailItemEventManagement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myMailItemEventManagement` DEFAULT CHARACTER SET utf8 ;
USE `myMailItemEventManagement` ;

-- -----------------------------------------------------
-- Table `myMailItemEventManagement`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myMailItemEventManagement`.`Address` (
  `AddresId` VARCHAR(36) NOT NULL,
  `PropertyNumber` VARCHAR(20) NULL,
  `Street` VARCHAR(45) NULL,
  `Locality` VARCHAR(45) NULL,
  `Town` VARCHAR(45) NULL,
  `County` VARCHAR(45) NULL,
  `PostCode` VARCHAR(10) NULL,
  `Country` VARCHAR(3) NULL,
  PRIMARY KEY (`AddresId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myMailItemEventManagement`.`MailItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myMailItemEventManagement`.`MailItem` (
  `UniqueItemId` VARCHAR(36) NOT NULL,
  `Status` VARCHAR(20) NULL DEFAULT NULL,
  `PreviousStatus` VARCHAR(20) NULL DEFAULT NULL,
  `EventCode` VARCHAR(30) NULL DEFAULT NULL,
  `WeightInGrammes` INT NULL DEFAULT NULL,
  `LengthInMillimetres` INT NULL DEFAULT NULL,
  `WidthInMillimetres` INT NULL DEFAULT NULL,
  `HeightInMillimetres` INT NULL DEFAULT NULL,
  `DeclaredLengthInMillimetres` INT NULL DEFAULT NULL,
  `DeclaredWidthInMillimetres` INT NULL DEFAULT NULL,
  `DeclaredHeightInMillimetres` INT NULL DEFAULT NULL,
  `ShapeType` VARCHAR(20) NULL DEFAULT NULL,
  `DestinationPostCode` VARCHAR(20) NULL DEFAULT NULL,
  `SourcePostCode` VARCHAR(20) NULL DEFAULT NULL,
  `CustomerAccountNumber` VARCHAR(20) NULL DEFAULT NULL,
  `RecipientAddresId` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`UniqueItemId`),
  INDEX `IDX-MAILITEM-UNIQUEITEMID` USING BTREE (`UniqueItemId` ASC),
  INDEX `fk_MailItem_Address1_idx` (`RecipientAddresId` ASC),
  CONSTRAINT `fk_MailItem_Address1`
    FOREIGN KEY (`RecipientAddresId`)
    REFERENCES `myMailItemEventManagement`.`Address` (`AddresId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myMailItemEventManagement`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myMailItemEventManagement`.`Events` (
  `EventId` VARCHAR(36) NULL,
  `TimeStamp` DATETIME NULL,
  `EventCode` VARCHAR(20) NULL,
  `ScannerId` VARCHAR(20) NULL,
  `LocationUnitCode` VARCHAR(45) NULL,
  `Longitude` FLOAT NULL,
  `Lattitude` FLOAT NULL,
  `MailItemUniqueItemId` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`EventId`, `MailItemUniqueItemId`),
  INDEX `fk_Events_MailItem_idx` (`MailItemUniqueItemId` ASC),
  CONSTRAINT `fk_Events_MailItem`
    FOREIGN KEY (`MailItemUniqueItemId`)
    REFERENCES `myMailItemEventManagement`.`MailItem` (`UniqueItemId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
